# Generated by Django 4.1.5 on 2023-01-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
